'use strict'

const ENG_LO = -108682.56
const ENG_HI = 108682.56
const RAW_HI = 9999
const RAW_LO = 0
const POWER_MULTIPLIER = (ENG_HI - ENG_LO) / (RAW_HI - RAW_LO)

const HI_ENG = 1
const LO_ENG = -1
const POWER_FACTOR_MULTIPLIER = (HI_ENG - LO_ENG) / 9999

const VOLTAGE_MULTIPLIER = 45360 / RAW_HI

const CURRENT_MULTIPLIER = 1198 / RAW_HI

const THD_MULTIPLIER = 1 / 1000

module.exports = {
  POWER_MULTIPLIER,
  POWER_FACTOR_MULTIPLIER,
  ENG_LO,
  LO_ENG,
  THD_MULTIPLIER,
  RAW_HI,
  VOLTAGE_MULTIPLIER,
  CURRENT_MULTIPLIER
}
